sudo: required
services:
  - docker
before_install:
  - docker build -t pedroluiznogueira/karbank-react -f Dockerfile.dev .
script:
  - docker run -e CI=true pedroluiznogueira/karbank-react npm run test
after_success:
  - docker build -t pedroluiznogueira/karbank-react .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pedroluiznogueira/karbank-react