sudo: required

services:
  - docker

before_install:
  - docker build -t pedroluiznogueira/kardbank-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pedroluiznogueira/kardbank-react npm run test -- --watch=false --coverage --passWithNoTests

after_success:
  - docker build -t pedroluiznogueira/kardbank-react .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pedroluiznogueira/kardbank-react