sudo: required

services:
  - docker

before_install:
  - docker build -t pedroluiznogueira/kardbank-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pedroluiznogueira/kardbank-react npm run test -- --watch=false --coverage --passWithNoTests

after_success:
  - docker build -t pedroluiznogueira/kardbank-react .
  - docker tag kardbank-react pedroluiznogueira/kardbank-react:"$VERSION"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pedroluiznogueira/kardbank-react && docker push pedroluiznogueira/kardbank-react:"$VERSION"

deploy:
  provider: heroku
  api_key:
    - secure: "$SECURE_KEY"
  app: "$APP"